- name: simple-provisioning
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: ap-northeast-2
    vpc_name: simple-vpc
    vpc_cidr_block: 10.210.0.0/16
    subnet_cidr_block: 10.210.1.0/24
    instance_image: ami-0b827f3319f7447c6
    ec2_key_name: btc_class3
    instance_type: t3.nano
    
  tasks:
  - name: create vpc
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ aws_region }}"
      tags:
        Name: "{{vpc_name}}"
      tenancy: default
    register: result_vpc
  - name: Create subnet
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ result_vpc.vpc.id }}"
      cidr: "{{ subnet_cidr_block}}"
      region: "{{ aws_region }}"
    register: result_subnet
  - name: Create igw
    ec2_vpc_igw:
      region: "{{ aws_region }}"
      vpc_id: "{{ result_vpc.vpc.id }}"
      state: present
    register: result_igw
  - name: Set up public subnet route table
    ec2_vpc_route_table:
      vpc_id: vpc-1245678
      region: "{{ aws_region }}"
      tags:
        Name: Public
      subnets:
        - "{{ result_subnet.subnet_id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ result_igw.gateway_id }}"
    register: public_route_table
    