- name: simple-provisioning
  hosts: localhost
  connection: localhost
  gather_facts: false
  vars:
    aws_region: ap=northeast-2 
	vpc_name: aimple-vpc_name
	vpc_cidr_block: 10.210.0.0/16
	subnet_cider_block: 10.210.1.0/24
	instancs_image: ami-0b827f3319f7447c6
    ec2_key_name: test
	instance_type: t3nano
  tasks:
  - name: create vpc
    ec2_vpc_net:
	  name : "{{ vpc_name }}"
	  cidr_block: "{{ vpc_cidr_block }}"
	  region: "{{ aws_region }}"
	  tags:
	    name: "{{ vpc_name }}"
	  tenancy: default
	register: result_vpc